master: scheduler MMU Process 
	gcc -o master master.c


scheduler:
	gcc -o scheduler scheduler.c

MMU:
	gcc -o MMU MMU.c

Process:
	gcc -o Process Process.c

clean:
	rm -f master scheduler MMU Process

