Master: sched MMU Process Master.c
	gcc -o Master Master.c


sched: sched.c
	gcc -o sched sched.c

MMU: MMU.c
	gcc -o MMU MMU.c

Process: Process.c
	gcc -o Process Process.c

clean:
	rm -f Master sched MMU Process output.txt

